const COLORS = {
    'Washington Capitols': 'black',
    'Philadelphia Warriors': 'black',
    'New York Knicks': 'black',
    'Providence Steamrollers': 'black',
    'Boston Celtics': 'black',
    'Toronto Huskies': 'black',
    'Chicago Stags': 'black',
    'St. Louis Bombers': 'black',
    'Cleveland Rebels': 'black',
    'Detroit Falcons': 'black',
    'Pittsburgh Ironmen': 'black',
    'Baltimore Bullets': 'black',
    'Rochester Royals': 'black',
    'Minneapolis Lakers': 'black',
    'Fort Wayne Pistons': 'black',
    'Indianapolis Jets': 'black',
    'Syracuse Nationals': 'black',
    'Indianapolis Olympians': 'black',
    'Anderson Packers': 'black',
    'Tri-Cities Blackhawks': 'black',
    'Sheboygan Red Skins': 'black',
    'Waterloo Hawks': 'black',
    'Denver Nuggets': 'black',
    'Milwaukee Hawks': 'black',
    'Angeles': 'black',
    'St. Louis Hawks': 'black',
    'Detroit Pistons': 'black',
    'Cincinnati Royals': 'black',
    'Los Angeles Lakers': 'black',
    'Chicago Packers': 'black',
    'San Francisco Warriors': 'black',
    'Chicago Zephyrs': 'black',
    'Philadelphia 76ers': 'black',
    'Chicago Bulls': 'black',
    'Seattle SuperSonics': 'black',
    'San Diego Rockets': 'black',
    'Milwaukee Bucks': 'black',
    'Atlanta Hawks': 'black',
    'Phoenix Suns': 'black',
    'Buffalo Braves': 'black',
    'Cleveland Cavaliers': 'black',
    'Portland Trail Blazers': 'black',
    'Golden State Warriors': 'black',
    'Houston Rockets': 'black',
    'Kansas City-Omaha Kings': 'black',
    'Capital Bullets': 'black',
    'Washington Bullets': 'black',
    'New Orleans Jazz': 'black',
    'Kansas City Kings': 'black',
    'San Antonio Spurs': 'black',
    'New York Nets': 'black',
    'Indiana Pacers': 'black',
    'New Jersey Nets': 'black',
    'San Diego Clippers': 'black',
    'Utah Jazz': 'black',
    'Dallas Mavericks': 'black',
    'Los Angeles Clippers': 'black',
    'Sacramento Kings': 'black',
    'Charlotte Hornets': 'black',
    'Miami Heat': 'black',
    'Orlando Magic': 'black',
    'Minnesota Timberwolves': 'black',
    'Toronto Raptors': 'black',
    'Vancouver Grizzlies': 'black',
    'Washington Wizards': 'black',
    'Memphis Grizzlies': 'black',
    'New Orleans Hornets': 'black',
    'Charlotte Bobcats': 'black',
    'New Orleans/Oklahoma City Hornets': 'black',
    'Oklahoma City Thunder': 'black',
    'Brooklyn Nets': 'black',
    "New Orleans Pelicans"
}